### ISSUE TITLE
Switch from `log` to `tracing`

### ISSUE THREAD

**Issue by NoxPardalis** [poetinger/rust_quickstart#3]
https://github.com/poetinger/rust_quickstart/blob/2458fc0c11f71756e14d3e8414b5506c2daba3d9/Cargo.toml#L13-L14

Should probably switch over to [`tracing`](https://crates.io/crates/tracing) and [`tracing-subscriber`](tracing-subscriber). If you use it like this you can still use the `log::*` macros.
```toml
log = { package = "tracing", version = "x.y.z" }
log-subscriber = { package = "tracing-subscriber", version = "x.y.z" }
```
